### ISSUE TITLE
Can I get a recent snapshot of the database?

### ISSUE THREAD

**Issue by dbieber** [sidneycadot/oeis#1]
Very glad to see this project :)! However, OEIS limits how quickly I can pull data from their website, so I expect it will take multiple days to download the database. Would it be possible to get a recent copy of the database from you? Maybe you could host a recent snapshot somewhere. Let me know if this is a possibility.

**Comment by sidneycadot** [comment]
Hi David,

I haven't actively worked on the project for some time. The latest snapshot I have is from August last year, is that useful to you? Compressed, it's a 2.6 GB file.

I just now find out that OEIS put constraints in place for crawling the database, which wasn't the case a year ago. This makes the process of crawling quite a bit harder. It is unfortunate that this was apparently necessary. I will have to figure out what the download rate limits are, I'll just ask on the mailing list.

I am planning to continue work on this project once time permits, but I am quite busy unfortunately.

**Comment by dbieber** [comment]
I was able to get everything I needed (just slowly), thanks.

**Comment by JesseWeinstein** [comment]
I'm interested in using this project to automatically upload copies of OEIS to archive.org, so it's backed up off-site. Thanks for your work on it!
